### ISSUE TITLE
screen might be flipped when it should not be?

### ISSUE THREAD

**Issue by Thelvaen** [geerlingguy/airgradient-prometheus#15]
considering the design of the case in the STLs provided by airgradient, it seems that the screw mounts are not in an orientation that would allow the screen to be read properly (it ends up on the top left instead of the bottom right corner.

Can I PR the following code:
```C++
// AirGradient case has its screws behind the screen with the fixation reverse compared
// to Jeff G. box, so flipping the screen is not necessary
// uncomment if you need/prefer having the screen on the bottom.
//#define flipScreen
```

and
```C++
  #ifdef flipScreen
  display.flipScreenVertically();
  #endif
```

**Comment by geerlingguy** [comment]
Yes; though I'd suggest for the description near the top where the variable is:

```
// Uncomment to flip the display 180 degrees.
```

No need for further explanation, I may consider changing the default in the future, though, if the case design is now inverted from what it was earlier last year.

**Comment by Thelvaen** [comment]
I believe it's no longer the same case, as you can see on that capture of my slicer screen the mounting screw holes make it pretty obvious that the fan on the PM2.5 sensor needs to be on the bottom, hence needing to flip the screen.

![mounting_screw](https://user-images.githubusercontent.com/19350574/148686264-148e5342-e89b-4872-bcdc-e98518b482e3.jpg)

That being said, it does not really make sense for the USB connector, because now it ends up on the top, and that's not good, I might sacrifice a USB cable to solder the 5V/GND directly to the board, but that's an other topic.
