### ISSUE TITLE
[Improvement Suggestion] Temperature sensor offset management

### ISSUE THREAD

**Issue by Thelvaen** [geerlingguy/airgradient-prometheus#19]
Hello,

SHT30/SHT31 as well as BME280 & other sensors of that kind typically have an offset of +/- 1°C, added to that the sensor enclosure & the proximity of other electronic component, the offset can easily rack up to a couple of °C.

Hence, in order to avoid recompiling and be able to simply tweak the offset to get a value as close to the real temperature as possible, I added some logic to the code available on my [BME280 fork](https://github.com/Thelvaen/airgradient-prometheus/blob/BME280/AirGradient-DIY/AirGradient-DIY.ino) to store the Temperature Offset in the EEPROM, setup a route to get/set the value, and each time the temperature is fetched (on screen display or scrapped by Prometheus) the offset is applied.

Feel free to add my code to yours, or to ask me to do a specific PR, if you want it without the BME280 extension.

**Comment by Benargee** [comment]
Not sure if this would satisfy your needs, but in Grafana you can add an offset of queried data. 
`atmp{job="airgradient-bedroom"} -1`
Not sure if you can add an offset for data being scraped by Prometheus.

**Comment by Thelvaen** [comment]
I mean, I implemented the offset on the sensor already (see my fork), so the value displayed by the sensor is correct as well.

**Comment by Benargee** [comment]
Understood, but this is a suggestion with much less complexity for those that it might suit.
