### ISSUE TITLE
Investigate use of ESPHome instead of a custom sketch

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/airgradient-prometheus#20]
After seeing @MallocArray's [airgradient_esphome](https://github.com/MallocArray/airgradient_esphome) project, I'm kinda wanting to see if I can not only replicate the Prometheus setup from this repo (see ESPHome's [Prometheus Component](https://github.com/MallocArray/airgradient_esphome)), but also get the thing integrated with my Home Assistant setup (video on that coming Wednesday).

That way you could use ESPHome and choose whether to use Prometheus or Home Assistant—or both!

**Comment by Choromanski** [comment]
[Video Referenced](https://www.youtube.com/watch?v=gJFsZL5CTgM)

**Comment by geerlingguy** [comment]
A few options now:

  - https://github.com/ajfriesen/ESPHome-AirGradient
  - https://github.com/MallocArray/airgradient_esphome
  - https://github.com/m-reiner/airgradient-esphome-prometheus

One really interesting aspect of @m-reiner's configuration is that it also builds a Prometheus scraping endpoint, which is quite nice to have available! You can integrate with HA and still have Prometheus/Grafana pulling down and displaying the data.

**Comment by m-reiner** [comment]
Thank you, @geerlingguy; it was very kind of you to reference my project!

I'm fairly new to the ESPHome side of things, so if either of you happen to know of better ways of accomplishing the things I did please let me know.  I can say that the config in my project has been working for me for around a week now, but that doesn't mean it can't be improved.

If you wanted to stick with Jeff's project but get the data into Home Assistant, one thing I did was create REST sensors in my HA configuration.yaml file like this:

```
#
  - platform: rest
    name: Office PM25
    resource: http://airgradient-ip-address:9926/
    scan_interval: 30
    unit_of_measurement: "µg/m³"
    value_template: '{{ value | regex_findall_index("pm02{[^}]*}\-?\d+\.?\d*") | regex_replace("^[^}]*}") }}'
  - platform: rest
    name: Office CO2
    resource: http://airgradient-ip-address:9926/
    scan_interval: 30
    unit_of_measurement: "ppm"
    value_template: '{{ value | regex_findall_index("rco2{[^}]*}\-?\d+\.?\d*") | regex_replace("^[^}]*}") }}'
  - platform: rest
    name: Office Temperature
    resource: http://airgradient-ip-address:9926/
    scan_interval: 30
    unit_of_measurement: "°C"
    value_template: '{{ value | regex_findall_index("atmp{[^}]*}\-?\d+\.?\d*") | regex_replace("^[^}]*}") }}'
  - platform: rest
    name: Office Humidity
    resource: http://airgradient-ip-address:9926/
    scan_interval: 30
    unit_of_measurement: "%"
    value_template: '{{ value | regex_findall_index("rhum{[^}]*}\-?\d+\.?\d*") | regex_replace("^[^}]*}") }}'
#
```

**Comment by geerlingguy** [comment]
Merged some code based on @m-reiner's and @ajfriesen's work!

![IMG_3633](https://user-images.githubusercontent.com/481677/201823053-55182af7-8291-4107-b175-47d2fb6dc51e.jpg)

**Comment by ajfriesen** [comment]
> A few options now:
> 
> * https://github.com/ajfriesen/ESPHome-AirGradient
> * https://github.com/MallocArray/airgradient_esphome
> * https://github.com/m-reiner/airgradient-esphome-prometheus
> 
> One really interesting aspect of @m-reiner's configuration is that it also builds a Prometheus scraping endpoint, which is quite nice to have available! You can integrate with HA and still have Prometheus/Grafana pulling down and displaying the data.

@geerlingguy 
You can also use the Prometheus integrations by Home Assistant itself and scrape that endpoint:
https://www.home-assistant.io/integrations/prometheus/

That way you get everything in Home Assistant into Prometheus 🙂
