### ISSUE TITLE
[Suggestion] SGP30 TVOC Sensor Support

### ISSUE THREAD

**Issue by IAm-ThePat** [geerlingguy/airgradient-prometheus#21]
Hi Mr. Geerling

First, I have to say that I love your video content!

I am creating this issue to discuss the possibility of adding support for the SGP30 sensor. 

AirGradient recently shared an article about using the SGP30 as a drop-in replacement for the SHT 3x, but mentioned that it can work in parallel as it is on the I2C bus. 

https://www.airgradient.com/resources/tvoc-on-airgradient-diy-sensor/

The SGP30 can report TVOC as well as equivalent CO2, H2 Hydrogen Molecules, and Ethanol. 

I've played around and tested, and was able to get it working using a sensor from AliExpress using the pin-out that corresponds to the headers on the left-hand side of the board

https://www.aliexpress.com/item/1005003085637996.html?spm=a2g0o.9042311.0.0.50054c4d7HX2mO

I have actually created a fork to make the changes in the arduino sketch, and am about to put in my first ever PR (yay)! I just wanted to add the issue in here for discussion. I am a total novice though, so don't be too hard on me :) and any advice or help would be appreciated!

A couple caveats:

- This requires the SGP30 library by RobTillaart
- The sensor didn't work right away, using the details from AirGradient, and I ended up having to change the console speed to 115200 (from the original 9600
- I went a little crazy, and am recording/displaying the values from all of the sensors. These can be removed if superfluous. 

Thanks!
-P

**Comment by Benargee** [comment]
In my humble opinion, I don't think this falls inside the scope of this project as this is just a sketch for the Air Gradient air quality kit as shipped and assembled. I think your implementation should remain your own fork.

**Comment by geerlingguy** [comment]
Agreed; this project's goal is to work out of the box with AirGradient's DIY kit, nothing more, nothing less. I'm happy to see forks pop up for broader use cases, of course (and that's why I use a permissive license ;).
