### ISSUE TITLE
Where's the PHP (the pi source files for the dashboard) ?

### ISSUE THREAD

**Issue by saormart** [geerlingguy/airgradient-prometheus#26]
Hi there, I was checking out your video, and I was trying to build the pi side but I just found the arduino source on this repository.
Where's the pi php files?

Thank you!

**Comment by geerlingguy** [comment]
That's all over in the https://github.com/geerlingguy/internet-pi repository.

**Comment by saormart** [comment]
It worked! 
Thank you!
