### ISSUE TITLE
ESP32 Async WebServer WebSocket JSON PID Controller Thermostat

### ISSUE THREAD

**Issue by mail87523** [geerlingguy/airgradient-prometheus#3]
Please try use upgrade make video if jou like ESP32 Async WebServer WebSocket JSON PID Controller Thermostat

**Comment by geerlingguy** [comment]
Thanks for the issue, I don't think this kind of thing would be helpful as an addition to this particular repository, as it doesn't have anything to do with the prometheus exporter, AFAICT.

**Comment by mail87523** [comment]
I not have your contact but I want to inform you about a useful home automation piece of device. 
You can also incorporate this project to your project like part of complete automation solution.
If you like you can upgrade it and make video on youtube.
