### ISSUE TITLE
OLED burn-in potential?

### ISSUE THREAD

**Issue by m-reiner** [geerlingguy/airgradient-prometheus#32]
I noticed that you seem to be using a single page to display all the data at once in the sensor package's OLED screen in your ESPHone sketch. 

I wanted to do the same thing, but ended up going with a rotation of pages (one for each sensor), similar to what you had in your original sketch, due to fears of OLED burn-in of the static elements/labels. 

Do you feel those fears are unwarranted or overblown? If so, I'd love to have a single page like yours!

**Comment by geerlingguy** [comment]
That's a good question. I'm willing to let it be for a while and see what happens, and see if it's a major problem or just a slight annoyance over time.

The main thing for me is I don't even look at the physical screen except once every month or two just to check on it when thinking about it, so it's not a big deal for me.
