### ISSUE TITLE
Add ESPHome configuration for AirGradient ONE

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/airgradient-prometheus#39]
The [AirGradient ONE](https://www.airgradient.com/airgradient-one/) is the latest and greatest sensor, and comes with a TVOC sensor (Sensirion SGP41) and 11 RGB LEDs (WS2812B) across the top of the device.

It would be cool if I could support the ONE for Home Assistant / ESPHome.

See build instructions for the v9 Pro pre-soldered kit: https://www.airgradient.com/open-airgradient/instructions/pro-v9/

**Comment by geerlingguy** [comment]
Looks like there's another config available here: https://forum.airgradient.com/t/new-airgradient-indoor-kit-monitor-available-now/1240/8

**Comment by geerlingguy** [comment]
I've added a config based on MallocArray's, and will be testing it out. Wanted to make LED brightness adjustable because at the default it lights up the whole room at night!

**Comment by zeuzere** [comment]
Thx for the MallocArray, It work great as is...
I added the color_correct  to reduce the overall brightness,
Exemple: 
    When red is set to 60% in the co2->on_value, 
     It mean the actual value will be 30% 
     because we set below the color_correct to 50%
_____
light:
    color_correct : [50%,50%,50%]

**Comment by stronk-dev** [comment]
Hi guys, just installed my airgradient one using this so thanks for that
The original script has some nice new additions to pull in (led control)
I also had to add `prometheus:` to the `.yaml` file to get the metrics endpoint exposed

**Comment by stronk-dev** [comment]
Another point of feedback: if not connected to home assistant it will reboot every 15 minutes: `[E][api:128]: No client connected to API. Rebooting...`

So for people who are only interested in the Prometheus endpoint they should comment out API access or add the following to the API block: `reboot_timeout: 0s`
