### ISSUE TITLE
Converting OLED Display from Celsius to Fahrenheit

### ISSUE THREAD

**Issue by dkeenes** [geerlingguy/airgradient-prometheus#7]
Has anyone modified the Arduino ino file to convert the temperature on the OLED display from Celsius to Fahrenheit?

**Comment by ArnaudKunzi** [comment]
Change line 94 https://github.com/geerlingguy/airgradient-prometheus/blob/b1ceb31e1c1cb506ad24e3c73cf4d1c29fc98fc7/AirGradient-DIY.ino#L94

into 

`showTextRectangle(String(result.t*9/5+32),String(result.rh)+"%",false);`
